version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: isi-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    container_name: isi-product-server
    restart: always
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql 
      DB_PORT: 3306
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_DATABASE}
    ports:
      - "3000:3000"
    volumes:
        - .:/app
        - /app/node_modules
    command: npm run dev

volumes:
  mysql-data: